# -*- coding: utf-8 -*-
"""Hospital Queue Management System with Priority Scheduling and Analytics.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nkLWEseCqtzXEzWvHH87m9DyzsvxUsYt
"""

# ==============================
# 🏥 FINAL LEVEL 2 HOSPITAL QUEUE SYSTEM (ERROR-FREE)
# ==============================

import pandas as pd
import time
import os
import matplotlib.pyplot as plt
from IPython.display import display, HTML, clear_output

# ==============================
# 📁 FILE SETUP
# ==============================
FILE = "patients.csv"

if not os.path.exists(FILE):
    df_init = pd.DataFrame(columns=["Token","Name","Priority","Time"])
    df_init.to_csv(FILE, index=False)

# ==============================
# 🔐 USERS
# ==============================
users = {
    "admin": "admin123",
    "reception": "1234"
}

# ==============================
# 🎨 UI FUNCTION
# ==============================
def ui(title, body):
    clear_output(wait=True)
    display(HTML(f"""
    <div style="font-family:Arial;background:#eef2f7;padding:20px">
        <h1 style="color:#1f4e79;">🏥 {title}</h1>
        <div style="background:white;padding:20px;border-radius:12px;
                    box-shadow:0 4px 10px rgba(0,0,0,0.1);">
            {body}
        </div>
    </div>
    """))

# ==============================
# 📥 LOAD DATA SAFE
# ==============================
def load_data():
    try:
        df = pd.read_csv(FILE)
        return df
    except:
        return pd.DataFrame(columns=["Token","Name","Priority","Time"])

# ==============================
# 💾 SAVE DATA
# ==============================
def save_data(df):
    df.to_csv(FILE, index=False)

# ==============================
# 🔐 LOGIN
# ==============================
def login():
    while True:
        ui("Login", "<h3>Enter credentials below</h3>")
        u = input("Username: ")
        p = input("Password: ")

        if u in users and users[u] == p:
            dashboard(u)
            break
        else:
            print("❌ Invalid credentials")
            time.sleep(1)

# ==============================
# 📊 DASHBOARD
# ==============================
def dashboard(user):
    while True:
        ui("Dashboard", f"""
        <h3>Welcome, {user}</h3>
        <p>Select an option:</p>
        <b>1</b> ➜ Add Patient<br>
        <b>2</b> ➜ View Queue<br>
        <b>3</b> ➜ Complete Patient<br>
        <b>4</b> ➜ Search Patient<br>
        <b>5</b> ➜ Analytics<br>
        <b>6</b> ➜ Logout
        """)

        choice = input("Enter choice: ").strip()

        if choice == "1":
            add_patient()
        elif choice == "2":
            view_queue()
        elif choice == "3":
            complete_patient()
        elif choice == "4":
            search_patient()
        elif choice == "5":
            analytics()
        elif choice == "6":
            break
        else:
            print("❌ Invalid choice")
            time.sleep(1)

# ==============================
# ➕ ADD PATIENT
# ==============================
def add_patient():
    df = load_data()

    name = input("Patient Name: ").strip()
    priority = input("Priority (Emergency/Normal): ").strip().capitalize()

    if priority not in ["Emergency", "Normal"]:
        print("❌ Invalid priority")
        time.sleep(1)
        return

    token = 1 if df.empty else int(df["Token"].max()) + 1

    new_row = pd.DataFrame([{
        "Token": token,
        "Name": name,
        "Priority": priority,
        "Time": time.strftime("%H:%M:%S")
    }])

    df = pd.concat([df, new_row], ignore_index=True)

    # Priority sorting
    df["Sort"] = df["Priority"].apply(lambda x: 0 if x == "Emergency" else 1)
    df = df.sort_values(by=["Sort", "Token"]).drop(columns=["Sort"])

    save_data(df)

    print(f"✅ Patient added! Token: {token}")
    time.sleep(1)

# ==============================
# 📋 VIEW QUEUE
# ==============================
def view_queue():
    df = load_data()

    if df.empty:
        print("⚠️ No patients in queue")
    else:
        df = df.copy()
        avg_time = 5
        df["Waiting(min)"] = [i * avg_time for i in range(len(df))]
        display(df)

    input("Press Enter to continue...")

# ==============================
# ✔️ COMPLETE PATIENT
# ==============================
def complete_patient():
    df = load_data()

    if df.empty:
        print("⚠️ No patients")
        time.sleep(1)
        return

    display(df)

    try:
        token = int(input("Enter Token to complete: "))
        if token in df["Token"].values:
            df = df[df["Token"] != token]
            save_data(df)
            print("✅ Patient completed")
        else:
            print("❌ Token not found")
    except:
        print("❌ Invalid input")

    time.sleep(1)

# ==============================
# 🔍 SEARCH
# ==============================
def search_patient():
    df = load_data()

    name = input("Enter patient name: ").strip()

    result = df[df["Name"].str.contains(name, case=False, na=False)]

    if result.empty:
        print("❌ No matching patient")
    else:
        display(result)

    input("Press Enter to continue...")

# ==============================
# 📊 ANALYTICS
# ==============================
def analytics():
    df = load_data()

    if df.empty:
        print("⚠️ No data available")
        time.sleep(1)
        return

    counts = df["Priority"].value_counts()

    plt.figure()
    counts.plot(kind="bar")
    plt.title("Patient Priority Distribution")
    plt.xlabel("Priority")
    plt.ylabel("Count")
    plt.show()

    input("Press Enter to continue...")

# ==============================
# 🚀 START SYSTEM
# ==============================
login()